collections:
  - name: kubernetes.core
    version: 5.0.0
    source: https://console.redhat.com/api/automation-hub/

  - name: redhat.openshift_virtualization
    version: 2.0.0
    source: https://console.redhat.com/api/automation-hub/

  - name: redhat.insights
    version: 1.3.0
    source: https://console.redhat.com/api/automation-hub/

  - name: redhat.satellite
    version: 4.1.0
    source: https://console.redhat.com/api/automation-hub/

  - name: ansible.controller
    version: 4.5.8
    source: https://console.redhat.com/api/automation-hub/

  - name: amazon.aws
    version: 8.1.0
    source: https://console.redhat.com/api/automation-hub/

  - name: ansible.posix
    version: 1.5.4
    source: https://galaxy.ansible.com

  - name: community.libvirt
    version: 1.3.0
    source: https://galaxy.ansible.com

  - name: community.docker
    version: 3.11.0
    source: https://galaxy.ansible.com

  - name: community.general
    version: 9.2.0
    source: https://galaxy.ansible.com

  - name: infra.aap_utilities
    version: 2.5.2
    source: https://galaxy.ansible.com

  - name: infra.ee_utilities
    version: 3.2.0
    source: https://galaxy.ansible.com

  - name: infra.ah_configuration
    version: 2.0.6
    source: https://galaxy.ansible.com

  - name: infra.controller_configuration
    version: 2.9.0
    source: https://galaxy.ansible.com

  - name: infra.eda_configuration
    version: 1.1.0
    source: https://galaxy.ansible.com
